preset: recommended
risky: true

version: 8.1

finder:
  exclude:
    - docs
    - vendor

enabled:
  - array_push
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - combine_nested_dirname
  - declare_strict_types
  - dir_constant
  - empty_loop_body_braces
  - fully_qualified_strict_types
  - function_to_constant
  - is_null
  - logical_operators
  - modernize_types_casting
  - native_function_type_declaration_casing
  - no_alias_functions
  - no_empty_comment
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_superfluous_elseif
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_useless_else
  - normalize_index_brace
  - php_unit_dedicate_assert
  - php_unit_dedicate_assert_internal_type
  - php_unit_expectation
  - php_unit_mock
  - php_unit_mock_short_will_return
  - php_unit_namespaced
  - php_unit_no_expectation_annotation
  - phpdoc_no_empty_return
  - phpdoc_property
  - phpdoc_trim_consecutive_blank_line_separation
  - phpdoc_type_to_var
  - phpdoc_types_order
  - regular_callable_call
  - self_accessor
  - self_static_accessor
  - set_type_to_cast
  - short_list_syntax
  - simplified_if_return
  - ternary_to_null_coalescing
  - unalign_double_arrow

disabled:
  - function_declaration
