on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  phpunit-uozp:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      before-hook: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool m4 make gcc
        git clone https://github.com/zonuexe/uopz.git /tmp/uopz
        cd /tmp/uopz && git checkout support/php84-exit
        phpize && ./configure && make && sudo make install
        PHP_INI_DIR=$(php-config --ini-dir)
        sudo mkdir -p "$PHP_INI_DIR"
        sudo sh -c "echo 'extension=uopz' > '$PHP_INI_DIR/uopz.ini'"
      concurrency-group: phpunit-uozp${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd
      os: '["ubuntu-latest"]'
      php-version: '["8.4"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

