---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: build

permissions:
  contents: read

jobs:
  phpunit:
    uses: yii2-framework/actions/.github/workflows/phpunit.yml@v1
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd, runkit7
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  phpunit-dev:
    uses: yii2-framework/actions/.github/workflows/phpunit.yml@v1
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}-dev
      extensions: mbstring, gd
      ignore-platform-reqs: true
      os: '["ubuntu-latest"]'
      php-version: '["8.5","8.6"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
