---
on:
  pull_request:
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push:
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@v2
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd, runkit7
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
