on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd
      phpunit-exclude-group: risky
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  phpunit-risky:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      concurrency-group: phpunit-risky-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd
      phpunit-configuration: tests/phpunit.xml.dist
      phpunit-group: risky
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
