on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      before-hook: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool m4 make gcc
        git clone https://github.com/krakjoe/uopz.git /tmp/uopz
        cd /tmp/uopz && sed -i '127s/^/\/\//' src/handlers.c
        phpize && ./configure && make && sudo make install
        PHP_INI_DIR=$(php-config --ini-dir)
        sudo mkdir -p "$PHP_INI_DIR"
        sudo sh -c "echo 'extension=uopz' > '$PHP_INI_DIR/uopz.ini'"
        php -m | grep uopz
      extensions: mbstring, gd
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
