on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  phpunit-uozp:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      concurrency-group: phpunit-uozp${{ github.workflow }}-${{ github.ref }}
      extensions: mbstring, gd, uozp
      php-version: '["8.0"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

