---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: Composer require checker

permissions:
  contents: read
  pull-requests: write

jobs:
  composer-require-checker:
    uses: php-forge/actions/.github/workflows/composer-require-checker.yml@v2
