on:
  pull_request:
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push:
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

name: Composer require checker

jobs:
  composer-require-checker:
    uses: php-forge/actions/.github/workflows/composer-require-checker.yml@v2
