---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: ecs

permissions:
  contents: read
  pull-requests: write

jobs:
  easy-coding-standard:
    uses: php-forge/actions/.github/workflows/ecs.yml@v2
