---
on:
  - pull_request
  - push

name: linter

permissions:
  checks: write
  contents: read
  statuses: write

jobs:
  linter:
    uses: php-forge/actions/.github/workflows/super-linter.yml@v2
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
