on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: mutation test

jobs:
  mutation:
    uses: php-forge/actions/.github/workflows/infection.yml@main
    with:
      before-hook: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool m4 make gcc
        git clone https://github.com/zonuexe/uopz.git /tmp/uopz
        cd /tmp/uopz && git checkout support/php84-exit
        phpize && ./configure && make && sudo make install
        PHP_INI_DIR=$(php-config --ini-dir)
        sudo mkdir -p "$PHP_INI_DIR"
        sudo sh -c "echo 'extension=uopz' > '$PHP_INI_DIR/uopz.ini'"
      php-version: '["8.4"]'
      phpstan: true
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
