---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: mutation test

permissions:
  contents: read
  pull-requests: write

jobs:
  mutation:
    uses: yii2-framework/actions/.github/workflows/infection.yml@v1
    with:
      extensions: runkit7-4.0.0a6
      php-version: '["8.3"]'
      phpstan: true
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
