on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"

  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"

name: mutation test

jobs:
  mutation:
    uses: php-forge/actions/.github/workflows/infection.yml@v2
    with:
      extensions: runkit7-4.0.0a6
      php-version: '["8.3"]'
      phpstan: true
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
