---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: static analysis

permissions:
  contents: read
  pull-requests: write

jobs:
  phpstan:
    uses: php-forge/actions/.github/workflows/phpstan.yml@v2
